version: "3.9"

services:
  api:
    build: .
    container_name: lynkar-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - lynkar-net

networks:
  lynkar-net:
    external: true
